#!/usr/bin/env python3
"""Generate screw-down ("M") variants of the stack-chan feet.

The pedestal (../enclosure/pedestal-sg90.scad) now retains the feet with 4x
M2x8 pan-head screws driven from inside the cavity, up through the 2 mm recess
floor, into pilot holes in the feet pads. The vendored feet have no holes, so
this script drills them.

Hole pattern (feet-local frame: hub/pan axis at origin, Z=0 = bottom face):
    4x Ø1.6 x 6.5 deep at (±12.5, -18) and (±12.5, +10)
All four spots were verified solid through the full 8.2 mm height (2026-06-12
ray-cast survey); the horn pocket floor is at Z 5.7 but only inside its cross
footprint (x -16.1..18.1, y ±8.4), which the holes avoid, so 6.5 mm is safe.
Ø1.6 matches the M2 self-tap pilot used everywhere else in the pedestal.

Inputs : feet_SG90.step, feet_MG90S2.step  (originals, untouched; the MG90S2
         feet are themselves generated by make_mg90s2.py — run that first if
         regenerating from scratch)
Outputs: feet_SG90M.step, feet_SG90M.stl, feet_MG90S2M.step, feet_MG90S2M.stl

Run with the CAD venv (pyenv 3.11 + build123d, see memory/cad-editing-toolchain):
    python make_feet_mounting.py
"""
import os
import sys
from build123d import (
    import_step, export_step, export_stl, Pos, Cylinder, Compound,
)

HERE = os.path.dirname(os.path.abspath(__file__))

PILOT_D = 1.6      # M2 self-tap pilot
PILOT_DEPTH = 6.5  # from the bottom face (M2x8 through the 2 mm floor -> 6 mm in)
HOLE_PTS = [(12.5, -18.0), (-12.5, -18.0), (12.5, 10.0), (-12.5, 10.0)]
HOLE_VOL = 3.14159 * (PILOT_D / 2) ** 2 * PILOT_DEPTH  # ~13.1 mm^3


def shp(x):
    """Coerce boolean results (ShapeList etc.) to a single Shape/Compound."""
    if hasattr(x, "volume"):
        return x
    return Compound(list(x))


def cut(solid, tool, label, min_dv=0.5):
    v0 = solid.volume
    out = shp(solid - tool)
    dv = v0 - out.volume
    assert dv > min_dv, f"{label}: cut removed only {dv:.3f}mm^3 (silent no-op?)"
    print(f"  {label}: -{dv:.1f}mm^3")
    return out


def drill(name):
    feet = import_step(os.path.join(HERE, f"{name}.step")).solids()[0]
    bb = feet.bounding_box()
    # sanity: both feet variants share the feet_SG90 frame (hub at origin,
    # bbox 48 x 37 x 8.2 with min Z = 0)
    assert abs(bb.min.X + 24.0) < 0.1 and abs(bb.max.X - 24.0) < 0.1, bb
    assert abs(bb.min.Y + 23.0) < 0.1 and abs(bb.max.Y - 14.0) < 0.1, bb
    assert abs(bb.min.Z) < 0.05, bb
    for x, y in HOLE_PTS:
        feet = cut(feet, Pos(x, y, PILOT_DEPTH / 2) * Cylinder(PILOT_D / 2, PILOT_DEPTH),
                   f"{name}: pilot at ({x:+.1f},{y:+.1f})", min_dv=HOLE_VOL * 0.8)
    return feet


def main():
    for name in ("feet_SG90", "feet_MG90S2"):
        print(f"{name}:")
        drilled = drill(name)
        export_step(drilled, os.path.join(HERE, f"{name}M.step"))
        export_stl(drilled, os.path.join(HERE, f"{name}M.stl"),
                   tolerance=0.05, angular_tolerance=0.3)
        bb = drilled.bounding_box()
        print(f"  -> {name}M vol={drilled.volume:.0f} "
              f"bbox Z {bb.min.Z:.2f}..{bb.max.Z:.2f}")
    print("done")


if __name__ == "__main__":
    sys.exit(main())
